server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bank
    password: bankpass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:super-secret-key-change-me}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
